---
- name: Define o arquivo de configuração do Postfix
  
  template: 
    src: main.cf.j2 
    dest: /etc/postfix/main.cf 
    owner: root 
    group: root 
    mode: 0644
  
  when:
    - result is sucess
  notify:
          - Reload Postfix
...
